apiVersion: v1
kind: PresistentVolume
metadata:
    name: nginx-pv
spec:
    capacity:
       storage: 5Gi
    accessModes:
       - ReadWriteOnce
    persistentVolumeReclaimPolicy: Retain
    hostPath:
       path: "/data/nginx"    # Adjust this path

---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
    name: nginx-pvc
spec:
   accessModes:
      - ReadWriteOnce
   resources:
     requests:
       storage: 1Gi
---
apiVersion: v1
kind: Service
metadata:
  name: nginx-headless
spec: 
   ClusterIP: None
   selector:
      app:nginx
    ports: 
      - protocol: TCP
        port: 80
        targetPort: 80
---
apiVersion: apps/v1
kind: StatefulSet
metadata: 
   name: nginx
spec:
   serviceName: "nginx"
   replicas: 2
   selector:
      matchLabels:
          app: nginx
   templates:
       metadata:
           labels:
              app: nginx
      spec:
        containers:
            - name: nginx
              image: secure-nginx:1.19
              ports:
                - containerPort: 80
              volumeMounts:
                 - name: nginx-storage
                   mountPath: /var/log/nginx
              resources:
                  requests:
                     cpu: "100m"
                     memory: "128Mi"
                  limits: 
                      cpu: "500m"
                      memory: "512Mi"
  volumeClaimTemplates:
      - metadata: 
           name: nginx-storage
        spec:
            accessModes: ["ReadWriteOnce"]
            resources:
               requests:
                  storage: 1Gi
